In [5]:
import pandas as pd

In [11]:
#Importar y leer el archivo CSV
df_energia = pd.read_csv("consumo_energia_iot.csv")
df_energia

,ID_Medidor,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
0,MED-5001,Villamaría,Estrato 3,130.5,118.0,32.74,Monofásico Digital,Al Día
1,MED-5002,Palestina,Estrato 2,175.0,120.5,19.97,Bifásico Inteligente,Al Día
2,MED-5003,Palestina,Estrato 1,220.0,118.0,11.71,Bifásico Inteligente,Mora
3,MED-5004,Neira,Estrato 4,130.5,128.0,64.26,Monofásico Digital,Al Día
4,MED-5005,Neira,Estrato 3,175.0,120.5,14.13,Monofásico Digital,Mora
...,...,...,...,...,...,...,...,...
1007,MED-5088,Villamaría,Estrato 2,220.0,118.0,34.78,Trifásico Industrial,Al Día
1008,MED-5089,Manizales,Estrato 3,220.0,122.0,62.85,Monofásico Digital,Al Día
1009,MED-5090,Villamaría,Estrato 2,290.5,120.5,39.57,Bifásico Inteligente,Al Día
1010,MED-5091,Palestina,Estrato 3,290.5,122.0,14.73,Trifásico Industrial,Al Día
1011,MED-5092,Neira,Estrato 3,220.0,120.5,22.41,Trifásico Industrial,Financiado

In [30]:
#Selección Unidimensional
serie_consumo = df_energia["Consumo_kWh"]
serie_consumo

0       130.5
1       175.0
2       220.0
3       130.5
4       175.0
        ...
1007    220.0
1008    220.0
1009    290.5
1010    290.5
1011    220.0
Name: Consumo_kWh, Length: 1012, dtype: float64

In [29]:
#proyeccion tabular
vista = df_energia[["Municipio", "Estrato", "Voltaje_Promedio"]]
vista

       Municipio    Estrato  Voltaje_Promedio
0     Villamaría  Estrato 3             118.0
1      Palestina  Estrato 2             120.5
2      Palestina  Estrato 1             118.0
3          Neira  Estrato 4             128.0
4          Neira  Estrato 3             120.5
...          ...        ...               ...
1007  Villamaría  Estrato 2             118.0
1008   Manizales  Estrato 3             122.0
1009  Villamaría  Estrato 2             120.5
1010   Palestina  Estrato 3             122.0
1011       Neira  Estrato 3             120.5

[1012 rows x 3 columns]

In [ ]:
#Consulta de Lectura Específica (loc)
fila_150 = df_energia.loc[150]
fila_150

ID_Medidor                      MED-5151
Municipio                          Neira
Estrato                        Estrato 2
Consumo_kWh                        130.5
Voltaje_Promedio                   112.5
Horas_Pico_kWh                     31.42
Tipo_Medidor        Trifásico Industrial
Estado_Pago                   Financiado
Name: 150, dtype: object

In [33]:
#Depuración de duplicados
df_energia = df_energia.drop_duplicates()
df_energia

,ID_Medidor,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
0,MED-5001,Villamaría,Estrato 3,130.5,118.0,32.74,Monofásico Digital,Al Día
1,MED-5002,Palestina,Estrato 2,175.0,120.5,19.97,Bifásico Inteligente,Al Día
2,MED-5003,Palestina,Estrato 1,220.0,118.0,11.71,Bifásico Inteligente,Mora
3,MED-5004,Neira,Estrato 4,130.5,128.0,64.26,Monofásico Digital,Al Día
4,MED-5005,Neira,Estrato 3,175.0,120.5,14.13,Monofásico Digital,Mora
...,...,...,...,...,...,...,...,...
995,MED-5996,Villamaría,Estrato 2,175.0,120.5,15.18,Monofásico Digital,Al Día
996,MED-5997,Villamaría,Estrato 2,175.0,125.5,13.07,Trifásico Industrial,Al Día
997,MED-5998,Palestina,Estrato 1,130.5,125.5,42.16,Monofásico Digital,Al Día
998,MED-5999,Neira,Estrato 3,175.0,120.5,60.44,Trifásico Industrial,Al Día
999,MED-6000,Palestina,Comercial,NaN,120.5,23.32,Monofásico Digital,Al Día

In [34]:
#Filtrado booleano simple
alto_consumo = df_energia[df_energia["Consumo_kWh"] > 250.0]
alto_consumo

,ID_Medidor,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
13,MED-5014,Neira,Estrato 4,290.5,112.5,69.74,Bifásico Inteligente,Al Día
16,MED-5017,Palestina,Estrato 1,290.5,118.0,12.81,Trifásico Industrial,Al Día
29,MED-5030,Manizales,Estrato 1,360.0,122.0,74.21,Monofásico Digital,Financiado
30,MED-5031,Neira,Estrato 2,290.5,125.5,6.57,Bifásico Inteligente,Financiado
40,MED-5041,Manizales,Estrato 2,290.5,122.0,66.32,Trifásico Industrial,Al Día
...,...,...,...,...,...,...,...,...
974,MED-5975,Manizales,Estrato 3,290.5,120.5,52.63,Bifásico Inteligente,Al Día
981,MED-5982,Neira,Estrato 1,290.5,122.0,25.36,Bifásico Inteligente,Al Día
982,MED-5983,Neira,Estrato 1,290.5,120.5,42.46,Bifásico Inteligente,Al Día
987,MED-5988,Palestina,Estrato 3,480.0,120.5,71.90,Bifásico Inteligente,Al Día
988,MED-5989,Palestina,Estrato 4,360.0,112.5,10.73,Monofásico Digital,Mora

In [35]:
#Filtrado categórico
subset = df_energia[df_energia["Municipio"].isin(["Chinchiná", "Villamaría"])]
subset

,ID_Medidor,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
0,MED-5001,Villamaría,Estrato 3,130.5,118.0,32.74,Monofásico Digital,Al Día
5,MED-5006,Chinchiná,Estrato 4,175.0,120.5,50.49,Bifásico Inteligente,Financiado
8,MED-5009,Villamaría,Estrato 2,130.5,122.0,45.63,Bifásico Inteligente,Mora
14,MED-5015,Chinchiná,Estrato 3,130.5,118.0,5.48,Bifásico Inteligente,Al Día
15,MED-5016,Chinchiná,Estrato 3,95.0,118.0,49.84,Monofásico Digital,Al Día
...,...,...,...,...,...,...,...,...
989,MED-5990,Villamaría,Estrato 2,220.0,118.0,44.74,Bifásico Inteligente,Al Día
993,MED-5994,Villamaría,Estrato 2,130.5,122.0,32.72,Bifásico Inteligente,Financiado
994,MED-5995,Chinchiná,Estrato 3,130.5,NaN,75.91,Trifásico Industrial,Al Día
995,MED-5996,Villamaría,Estrato 2,175.0,120.5,15.18,Monofásico Digital,Al Día
996,MED-5997,Villamaría,Estrato 2,175.0,125.5,13.07,Trifásico Industrial,Al Día

In [36]:
#Filtrado por intervalo numérico
voltaje_optimo = df_energia[df_energia["Voltaje_Promedio"].between(118.0, 122.0)]
voltaje_optimo

,ID_Medidor,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
0,MED-5001,Villamaría,Estrato 3,130.5,118.0,32.74,Monofásico Digital,Al Día
1,MED-5002,Palestina,Estrato 2,175.0,120.5,19.97,Bifásico Inteligente,Al Día
2,MED-5003,Palestina,Estrato 1,220.0,118.0,11.71,Bifásico Inteligente,Mora
4,MED-5005,Neira,Estrato 3,175.0,120.5,14.13,Monofásico Digital,Mora
5,MED-5006,Chinchiná,Estrato 4,175.0,120.5,50.49,Bifásico Inteligente,Financiado
...,...,...,...,...,...,...,...,...
992,MED-5993,Neira,Estrato 1,95.0,120.5,41.06,Trifásico Industrial,Al Día
993,MED-5994,Villamaría,Estrato 2,130.5,122.0,32.72,Bifásico Inteligente,Financiado
995,MED-5996,Villamaría,Estrato 2,175.0,120.5,15.18,Monofásico Digital,Al Día
998,MED-5999,Neira,Estrato 3,175.0,120.5,60.44,Trifásico Industrial,Al Día
999,MED-6000,Palestina,Comercial,NaN,120.5,23.32,Monofásico Digital,Al Día

In [37]:
#Consulta con query
comercial_mora = df_energia.query("Estrato == 'Comercial' and Estado_Pago == 'Mora'")
comercial_mora

,ID_Medidor,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
58,MED-5059,Villamaría,Comercial,290.5,122.0,75.92,Trifásico Industrial,Mora
84,MED-5085,Manizales,Comercial,220.0,118.0,38.27,Monofásico Digital,Mora
95,MED-5096,Chinchiná,Comercial,130.5,128.0,47.36,Monofásico Digital,Mora
115,MED-5116,Villamaría,Comercial,175.0,120.5,74.32,Monofásico Digital,Mora
129,MED-5130,Chinchiná,Comercial,95.0,120.5,44.48,Monofásico Digital,Mora
154,MED-5155,Villamaría,Comercial,NaN,120.5,82.10,Monofásico Digital,Mora
203,MED-5204,Palestina,Comercial,220.0,120.5,24.62,Bifásico Inteligente,Mora
238,MED-5239,Villamaría,Comercial,95.0,120.5,37.48,Monofásico Digital,Mora
253,MED-5254,Neira,Comercial,220.0,122.0,60.39,Monofásico Digital,Mora
281,MED-5282,Chinchiná,Comercial,290.5,128.0,75.34,Monofásico Digital,Mora
290,MED-5291,Palestina,Comercial,220.0,112.5,73.90,Bifásico Inteligente,Mora
328,MED-5329,Manizales,Comercial,NaN,120.5,44.94,Monofásico Digital,Mora
348,MED-5349,Manizales,Comercial,95.0,118.0,50.55,Monofásico Digital,Mora
467,MED-5468,Manizales,Comercial,175.0,120.5,8.51,Monofásico Digital,Mora
469,MED-5470,Villamaría,Comercial,290.5,118.0,58.66,Bifásico Inteligente,Mora
500,MED-5501,Chinchiná,Comercial,130.5,125.5,28.92,Monofásico Digital,Mora
501,MED-5502,Manizales,Comercial,220.0,118.0,56.56,Monofásico Digital,Mora
503,MED-5504,Villamaría,Comercial,220.0,122.0,65.62,Monofásico Digital,Mora
507,MED-5508,Chinchiná,Comercial,220.0,NaN,33.44,Monofásico Digital,Mora
527,MED-5528,Palestina,Comercial,360.0,125.5,52.83,Monofásico Digital,Mora
643,MED-5644,Chinchiná,Comercial,220.0,118.0,35.88,Monofásico Digital,Mora
667,MED-5668,Palestina,Comercial,95.0,118.0,72.71,Monofásico Digital,Mora
707,MED-5708,Palestina,Comercial,175.0,120.5,32.23,Monofásico Digital,Mora
737,MED-5738,Palestina,Comercial,360.0,122.0,81.48,Monofásico Digital,Mora
791,MED-5792,Villamaría,Comercial,175.0,128.0,58.12,Monofásico Digital,Mora
805,MED-5806,Villamaría,Comercial,290.5,120.5,52.04,Trifásico Industrial,Mora
821,MED-5822,Neira,Comercial,175.0,118.0,32.58,Monofásico Digital,Mora
832,MED-5833,Villamaría,Comercial,95.0,125.5,63.27,Monofásico Digital,Mora
849,MED-5850,Neira,Comercial,130.5,122.0,30.32,Monofásico Digital,Mora
863,MED-5864,Manizales,Comercial,175.0,122.0,68.23,Monofásico Digital,Mora
900,MED-5901,Palestina,Comercial,220.0,NaN,44.09,Monofásico Digital,Mora
936,MED-5937,Palestina,Comercial,220.0,118.0,81.29,Monofásico Digital,Mora

In [38]:
#Filtrado compuesto con texto
condicion = (df_energia["Tipo_Medidor"].str.startswith("B")) & (df_energia["Horas_Pico_kWh"] > 40.0)
resultado = df_energia[condicion]
resultado

,ID_Medidor,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
5,MED-5006,Chinchiná,Estrato 4,175.0,120.5,50.49,Bifásico Inteligente,Financiado
7,MED-5008,Palestina,Estrato 1,220.0,120.5,51.93,Bifásico Inteligente,Mora
8,MED-5009,Villamaría,Estrato 2,130.5,122.0,45.63,Bifásico Inteligente,Mora
13,MED-5014,Neira,Estrato 4,290.5,112.5,69.74,Bifásico Inteligente,Al Día
17,MED-5018,Palestina,Estrato 2,NaN,120.5,54.42,Bifásico Inteligente,Mora
...,...,...,...,...,...,...,...,...
979,MED-5980,Villamaría,Comercial,95.0,120.5,73.78,Bifásico Inteligente,Al Día
982,MED-5983,Neira,Estrato 1,290.5,120.5,42.46,Bifásico Inteligente,Al Día
987,MED-5988,Palestina,Estrato 3,480.0,120.5,71.90,Bifásico Inteligente,Al Día
989,MED-5990,Villamaría,Estrato 2,220.0,118.0,44.74,Bifásico Inteligente,Al Día
991,MED-5992,Neira,Estrato 3,95.0,118.0,50.10,Bifásico Inteligente,Mora

In [40]:
#Tratamiento de nulos
df_energia["Consumo_kWh"].fillna(df_energia["Consumo_kWh"].mean(), inplace=True)
df_energia["Voltaje_Promedio"].fillna(120.0, inplace=True)
df_energia

C:\Users\Galvis\AppData\Local\Temp\ipykernel_14424\3407555385.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_energia["Consumo_kWh"].fillna(df_energia["Consumo_kWh"].mean(), inplace=True)
C:\Users\Galvis\AppData\Local\Temp\ipykernel_14424\3407555385.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_energia["Voltaje_Promedio"].fillna(120.0, inplace=True)

,ID_Medidor,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
0,MED-5001,Villamaría,Estrato 3,130.5,118.0,32.74,Monofásico Digital,Al Día
1,MED-5002,Palestina,Estrato 2,175.0,120.5,19.97,Bifásico Inteligente,Al Día
2,MED-5003,Palestina,Estrato 1,220.0,118.0,11.71,Bifásico Inteligente,Mora
3,MED-5004,Neira,Estrato 4,130.5,128.0,64.26,Monofásico Digital,Al Día
4,MED-5005,Neira,Estrato 3,175.0,120.5,14.13,Monofásico Digital,Mora
...,...,...,...,...,...,...,...,...
995,MED-5996,Villamaría,Estrato 2,175.0,120.5,15.18,Monofásico Digital,Al Día
996,MED-5997,Villamaría,Estrato 2,175.0,125.5,13.07,Trifásico Industrial,Al Día
997,MED-5998,Palestina,Estrato 1,130.5,125.5,42.16,Monofásico Digital,Al Día
998,MED-5999,Neira,Estrato 3,175.0,120.5,60.44,Trifásico Industrial,Al Día
999,MED-6000,Palestina,Comercial,NaN,120.5,23.32,Monofásico Digital,Al Día

In [42]:
#Transformación condicional
def nivel_tarifa(consumo):
    if consumo < 120:
        return "Bajo"
    elif consumo <= 250:
        return "Medio"
    else:
        return "Alto"

df_energia["Nivel_Consumo"] = df_energia["Consumo_kWh"].apply(nivel_tarifa)
df_energia[["Consumo_kWh", "Nivel_Consumo"]]

     Consumo_kWh Nivel_Consumo
0          130.5         Medio
1          175.0         Medio
2          220.0         Medio
3          130.5         Medio
4          175.0         Medio
..           ...           ...
995        175.0         Medio
996        175.0         Medio
997        130.5         Medio
998        175.0         Medio
999          NaN          Alto

[1000 rows x 2 columns]

In [43]:
#Renombrado y reordenamiento
df_energia.rename(columns={"Consumo_kWh": "Energia_kWh", "Tipo_Medidor": "Tecnologia"}, inplace=True)

df_energia = df_energia[["ID_Medidor", "Nivel_Consumo"] + [col for col in df_energia.columns if col not in ["ID_Medidor", "Nivel_Consumo"]]]

df_energia

,ID_Medidor,Nivel_Consumo,Municipio,Estrato,Energia_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tecnologia,Estado_Pago
0,MED-5001,Medio,Villamaría,Estrato 3,130.5,118.0,32.74,Monofásico Digital,Al Día
1,MED-5002,Medio,Palestina,Estrato 2,175.0,120.5,19.97,Bifásico Inteligente,Al Día
2,MED-5003,Medio,Palestina,Estrato 1,220.0,118.0,11.71,Bifásico Inteligente,Mora
3,MED-5004,Medio,Neira,Estrato 4,130.5,128.0,64.26,Monofásico Digital,Al Día
4,MED-5005,Medio,Neira,Estrato 3,175.0,120.5,14.13,Monofásico Digital,Mora
...,...,...,...,...,...,...,...,...,...
995,MED-5996,Medio,Villamaría,Estrato 2,175.0,120.5,15.18,Monofásico Digital,Al Día
996,MED-5997,Medio,Villamaría,Estrato 2,175.0,125.5,13.07,Trifásico Industrial,Al Día
997,MED-5998,Medio,Palestina,Estrato 1,130.5,125.5,42.16,Monofásico Digital,Al Día
998,MED-5999,Medio,Neira,Estrato 3,175.0,120.5,60.44,Trifásico Industrial,Al Día
999,MED-6000,Alto,Palestina,Comercial,NaN,120.5,23.32,Monofásico Digital,Al Día

In [44]:
#Agregación por municipio
resumen_municipio = df_energia.groupby("Municipio").agg(
    consumo_promedio=("Energia_kWh", "mean"),
    horas_pico_total=("Horas_Pico_kWh", "sum")
)
resumen_municipio

            consumo_promedio  horas_pico_total
Municipio
Chinchiná         193.026882           8523.16
Manizales         199.976804           9008.74
Neira             192.547872           9124.80
Palestina         192.423469           9324.64
Villamaría        187.523810           8876.86

In [45]:
#Métricas de rango personalizadas
def rango(series):
    return series.max() - series.min()

resumen_estrato = df_energia.groupby("Estrato").agg(
    rango_consumo=("Energia_kWh", rango),
    rango_voltaje=("Voltaje_Promedio", rango)
)
resumen_estrato

           rango_consumo  rango_voltaje
Estrato
Comercial          385.0           15.5
Estrato 1          385.0           15.5
Estrato 2          385.0           15.5
Estrato 3          385.0           15.5
Estrato 4          385.0           15.5

In [46]:
#Agrupamiento multinivel
resumen_multi = df_energia.groupby(["Municipio", "Estrato"]).agg(
    consumo_promedio=("Energia_kWh", "mean"),
    voltaje_promedio=("Voltaje_Promedio", "mean")
)
resumen_multi

                      consumo_promedio  voltaje_promedio
Municipio  Estrato
Chinchiná  Comercial        188.115385        121.100000
           Estrato 1        184.027778        120.405405
           Estrato 2        205.702703        120.802632
           Estrato 3        196.818182        119.981132
           Estrato 4        185.968750        120.593750
Manizales  Comercial        181.648148        120.775862
           Estrato 1        222.088235        118.885714
           Estrato 2        186.532787        120.631148
           Estrato 3        219.364583        120.764706
           Estrato 4        184.666667        121.520833
Neira      Comercial        180.576923        120.379310
           Estrato 1        186.880000        119.705882
           Estrato 2        183.571429        120.121212
           Estrato 3        197.264706        120.260870
           Estrato 4        218.250000        119.958333
Palestina  Comercial        206.083333        119.950000
           Estrato 1        200.175676        121.039474
           Estrato 2        190.561404        120.245455
           Estrato 3        191.857143        120.717391
           Estrato 4        167.956522        121.704545
Villamaría Comercial        203.035714        120.862069
           Estrato 1        186.205882        120.114286
           Estrato 2        183.694915        120.700000
           Estrato 3        181.558140        120.025000
           Estrato 4        191.240000        119.565217